// <auto-generated />
using System;
using FamilyFoundsApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyFoundsApi.Persistence.Migrations
{
    [DbContext(typeof(FamilyFoundsDbContext))]
    partial class FamilyFoundsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Artykuły spożywcze"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Artykuły chemiczne i higieniczne"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Ubrania"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Rozrywka"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = (short)6,
                            Name = "Sprzęt domowy i budowlany"
                        },
                        new
                        {
                            Id = (short)7,
                            Name = "Zdrowie i uroda"
                        },
                        new
                        {
                            Id = (short)8,
                            Name = "Rachunki"
                        },
                        new
                        {
                            Id = (short)9,
                            Name = "Dzieci"
                        },
                        new
                        {
                            Id = (short)10,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.ImportSource", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ImportSource");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "ING"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "MILLENNIUM"
                        });
                });

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<short?>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Contractor")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContractorAccountNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContractorBankName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<short?>("ImportSourceId")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Number")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportSourceId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.Transaction", b =>
                {
                    b.HasOne("FamilyFoundsApi.Domain.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("FamilyFoundsApi.Domain.Models.ImportSource", "ImportSource")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportSourceId");

                    b.Navigation("Category");

                    b.Navigation("ImportSource");
                });

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FamilyFoundsApi.Domain.Models.ImportSource", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
